<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-27T21:26:11 IST" name="Suite" finished-at="2024-04-27T21:26:30 IST" duration-ms="19129">
    <groups>
    </groups>
    <test started-at="2024-04-27T21:26:11 IST" name="Test" finished-at="2024-04-27T21:26:30 IST" duration-ms="19129">
      <class name="com.ect.testcases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ect.testcases.LoginTest@2a3a299]" started-at="2024-04-27T21:26:12 IST" name="setup" finished-at="2024-04-27T21:26:20 IST" duration-ms="7676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify(java.lang.String,java.lang.String)[pri:0, instance:com.ect.testcases.LoginTest@2a3a299]" started-at="2024-04-27T21:26:20 IST" name="verify" data-provider="logindataProvider" finished-at="2024-04-27T21:26:28 IST" duration-ms="7155" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ravi@dhiyotech.in]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Demo]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method signature="verify(java.lang.String,java.lang.String)[pri:0, instance:com.ect.testcases.LoginTest@2a3a299]" started-at="2024-04-27T21:26:28 IST" name="verify" data-provider="logindataProvider" finished-at="2024-04-27T21:26:30 IST" duration-ms="2551" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[infotek@solutions.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Demo12]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.ect.testcases.LoginTest.verify(LoginTest.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
      </class> <!-- com.ect.testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
